on:
  push:
    branches:
      - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      -
        name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.eutenly.com
          username: eutenly
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: eutenly/bot:latest